name: Laravel CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Installer Docker et Docker Compose 
        run: |
          echo "sudo apt-get update"
          echo "sudo apt-get install -y docker.io docker-compose"
          echo "docker --version"
          echo "docker-compose --version"
          echo " Docker et Docker Compose (simulation) installés avec succès !"

      - name: Lancer les services avec Docker Compose 
        run: |
          echo "docker-compose up -d"
          echo "Docker Compose exécuté !"

      - name: Vérifier que les conteneurs tournent 
        run: |
          echo "docker ps -a"
          echo "Conteneurs Docker  en cours d'exécution !"

      - name: Installer les dépendances PHP 
        run: |
          echo "docker exec -i \$(docker ps -qf 'name=laravel') composer install"
          echo " Dépendances PHP  installées !"

      - name: Vérifier que l'application Laravel tourne bien 
        run: |
          echo "curl -Is http://localhost | head -n 1"
          echo " L'application Laravel tourne bien dans Docker !"
